<?php

return [
    'dir' => 'ltr',
    'title' => 'Naftal Helpdesk',
    'dashboard' => 'Dashboard',
    'langualge' => 'English',
    'platform_title' => 'Naftal',
    'platform_subtitle' => 'Platform for Equipment Complaints',
    'integrated_solution' => 'The integrated solution for managing your petroleum services',
    'description' => 'Naftal platform provides innovative solutions for managing and distributing petroleum products efficiently, ensuring transparency, security, and reliability in all your transactions.',

    'clients_active' => '5000+ Active Clients',
    'get_started' => 'Get Started',
    'learn_more' => 'Learn More',
    'fuel_stations' => '150+ Fuel Stations',
    'customer_satisfaction' => '99% Customer Satisfaction',
    'years_of_experience' => '25+ Years of Experience',

    'faq_title' => 'Frequently Asked Questions',
    'faq_description' => 'Answers to the most frequently asked questions about our services',

    'how_to_register' => 'How can I register on the platform?',
    'how_to_register_answer' => 'You can easily register on the platform by clicking the "Create Account" button at the top of the page, then entering your personal details and contact information. After completing the registration process, you will be able to access your dashboard and use all the available services.',

    'payment_methods' => 'What payment methods are available?',
    'fuel_delivery_time' => 'How long does the fuel delivery process take?',
    'cancel_order' => 'Can I cancel the order after confirming it?',

    'company_description' => 'Naftal is a leading company in the field of marketing and energy services, always striving to provide innovative solutions that meet its clients\' needs with the highest standards of quality and safety.',

    'footer' => 'Naftal Petroleum Services Company. All rights reserved.',
    'developper_walid' => 'Oualid Hamri Pages',
    'logout' => 'Logout',
    'login' => 'Login',
    'welcome_back'=> 'Welcome Back',
    'secure_login'=>'Secure Login',
    'home'=>'Home',
    'signin_text'=>'Sign in to access your Naftal account dashboard',
    'userid'=>'User Id',
    'Password'=>'Password',
    'remember_me'=>'Remember Me',
    'system'=> 'System Informations',
    'access'=>'Fast Access',
    'last_update'=>'Last Time Updated :',
    'support'=> 'support',
    'tickets'=> 'Tickets',
    'copyrights' => '2025 Naftal. All rights reserved.',
    'password'=>'Password',

    'document_title' => 'Tickets A Signé',
    'reference_number' => 'Reference No.: GSR-:id-:year',
    'looged_in_as'=> 'Logged in as',

    'request_details' => 'Request Details',
    'applicant_information' => 'Applicant Information',
    'profile'=>'profile',
    'settings'=>'settings',
    'employees'=> 'Workers',
    'ingenieurs' => 'Engineers',
    'faqs'=> 'FAQs',
    'add_employee'=> 'Add Employee',
    'list_employees'=> 'List Employees',
    'list_ingenieurs'=> 'List Engineers',
    'list_faqs'=> 'List FAQs',
    'editpassword'=>'Edit Password',
    'edit_employee'=> 'Edit Employee',
    'ticket_title'=> 'Tickets',
    'employee'=> 'Employee',
    'ingenieur'=> 'Engineer',
    'faq'=> 'FAQ',
    'status'=> 'Status',
    'id'=>'User Id',
    'date'=> 'Date',
    'actions'=> 'Actions',
    'add_faq'=> 'Add FAQ',
    'edit_faq'=> 'Edit FAQ',
    'add_ingenieur'=> 'Add Engineer',
    'total_employees'=>'Total Employees',
    'total_ingenieurs'=>'Total Engineers',
    'total_faqs'=>'Total FAQs',
    'total_tickets'=>'Total Tickets',
    'tickets_solved'=>'Tickets solved',
    'priority'=> 'Priority',
    'last_created_tickets'=>'Last Created Tickets',
    'traffic'=>'Traffic',
    


    'service_type' => 'Service Type:',
    'current_status' => 'Current Status:',
    'submission_date' => 'Submission Date:',
    'full_name' => 'Full Name:',
    'assigned_department' => 'Assigned Department:',

    'assignments'=> 'Assignments',
    'pending_assignment' => 'Pending Assignment',
    'closed' => 'CLOSED',
    'solved' => 'SOLVED',
    'pending' => 'PENDING',
    

    'footer_line1' => 'This document is automatically generated by the official government service system',
    'footer_line2' => 'All rights reserved © Government Services Department :year',
    

    'official_seal' => 'OFFICIAL SEAL',
    'government' => 'GOVERNMENT',
    
    'status_processed' => 'PROCESSED',
    'status_under_review' => 'UNDER REVIEW',
    
];
